language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
  - bundle exec ruby tests/test_helper.rb
  - bundle exec ruby tests/today_test.rb
  - bundle exec ruby tests/images_test.rb
  - bundle exec ruby tests/grammer_spelling_test.rb
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
