---
title: Bust A Mac
tagline: All the info you'll need to bust your Mac.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Uploads
    output: true
defaults:
- scope:
    path: '_posts'
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: '_pages'
    type: pages
  values:
    layout: page
permalink: pretty
include: ['_pages']
